### ISSUE TITLE
On mobile: Code text size is rather large and line numbers do not match up

### ISSUE THREAD

**Issue by DarrienG** [MayADevBe/Hugo-Gruvbox-Theme#2]
This gruvbox theme is great! I've been searching around for one for a while that doesn't require using npm to initialize and that works with newer hugo versions. Overall I love this one :)

I noticed however text size is rather large on mobile compared to on desktop (proportionally at least).

Desktop:

![Screen Shot 2022-03-05 at 8 14 47 PM](https://user-images.githubusercontent.com/5041953/156905038-73630fd6-b92c-4dfc-a7c5-d0fc9441b621.png)

Mobile:

![IMG_1482](https://user-images.githubusercontent.com/5041953/156905039-3ceb3cb0-24a4-4ed2-94ee-4fcda26bae45.PNG)

It's a little jarring how large the size difference is. Is there a configuration parameter I could tweak to decrease the code text size on mobile? It looks good on Desktop :) 

Full blog site if you need for testing: https://blog.darrien.dev

**Comment by DarrienG** [comment]
This may be an issue with chroma: https://github.com/MayADevBe/Hugo-Gruvbox-Theme/issues/5#issuecomment-1059882819 will follow up later with further investigation.

**Comment by MayADevBe** [comment]
I'm not sure about the line numbers. But the text size for mobile could be customized with the following code in the main.css:
```
@media (max-width: 600px){
    body{
        font-size: 0.8rem;
    }
}
```
Depending on your liking you could try changing max-width and font-size to fit the mobile devices. Maybe this will solve part of your problem.

**Comment by DarrienG** [comment]
That helps, thanks, although it does make everything rather small. I found the best way to do this was to add a section in syntax.css below the `.chroma .lntable { ... }` selector like so did what I needed:

```css
@media (max-width: 600px){
    .chroma .lntable {
        font-size: 0.6rem;
    }
}
```

With this absolutely terrible hack I added to my local syntax.css it gets the full behavior I want without line numbers too:

```css
/*
 * Just terrible, awful things. Line number tables get scrolling, while non-line number tables do not.
 * This means to get the display we want, we need to pick line number tables, but hide the line numbers.
 * I'm sorry....
 */
.chroma .lntable td:first-child {
    display: none;
}
```

Anyway, probably not something to commit to the main theme, but for folks looking to get around it, I guess this will do it.

I'm guessing to do this properly for tables without line numbers we'd want to add `width: auto; overflow: auto; display: block;` to whatever class code fenced areas without line numbers use, but I'm really fine with this solution as long as it works.

With that said I should really learn css so I can do this properly some day......

Closing this out, thanks again for the help!
